name: Build Windows App

on:
  push:
    branches: [ "source", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64

    - name: Enable desktop support
      run: |
        flutter config --enable-windows-desktop

    - name: Install dependencies
      run: flutter pub get

    - name: Generate App Icons
      run: dart run flutter_launcher_icons

    - name: Build Windows release
      run: flutter build windows --release

    - name: Bundle C++ Runtime DLLs
      run: |
        Copy-Item -Path "C:\Windows\System32\msvcp140.dll" -Destination "build\windows\x64\runner\Release\"
        Copy-Item -Path "C:\Windows\System32\vcruntime140.dll" -Destination "build\windows\x64\runner\Release\"
        Copy-Item -Path "C:\Windows\System32\vcruntime140_1.dll" -Destination "build\windows\x64\runner\Release\"

    - name: Compile Inno Setup Script
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: windows\installer.iss

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sabuflix-Installer
        path: windows\Output\Sabuflix-Setup.exe
